### ISSUE TITLE
ufldl的源码太复杂了.

### ISSUE THREAD

**Issue by jawaechan** [yhfudev/doc-ml-ufldl#1]
ufldl的源码太复杂了. 在电脑上编译不成功, 缺各种字体,能否提供一个纯英文的源码文件?不需要加载太多字体的.

**Comment by yhfudev** [comment]
Hi,
You may change the font names in the file cndoc.tex,
or change the definition to LANG=en in the file Makefile.

2015-06-17 1:04 GMT-04:00 Jawae notifications@github.com:
